AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
  - './lib/**/_OLD/**'
  - 'vendor/**/*'

Style/ClassVars:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
  - './lib/**/cli.rb'
  - './lib/**/onlinesearch.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
  - './lib/**/cli.rb'
  - './lib/**/onlinesearch.rb'

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
  - './lib/**/onlinesearch.rb'
  - './lib/**/data.rb'

Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
  - './lib/**/onlinesearch.rb'
  - './lib/**/data.rb'

Lint/UriEscapeUnescape:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  Exclude:
  - './lib/**/data.rb'

Security/MarshalLoad:
  Enabled: true
  Exclude:
  - './lib/**/cache.rb'

Style/SingleLineMethods:
  Enabled: true
  Exclude:
  - './lib/**/utils.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
  - './bin/*'
  - './exe/*'
